name: Run Tests

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build -t qa-portfolio .

    - name: Run tests in Docker
      run: docker run --rm qa-portfolio